
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-19T14:30:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e9b7d4a62f6efb3d282d9ded2baf4625fab0515",
 "version": "2022.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
